Repository destroyersworld007/CppCodeCollection, pull requests merged in 2022-10, with the labels that each got.

#1 Create basic.cpp
  basic.cpp
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#2 handler.cpp
  README.md
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#3 star.html
  star.html
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#4 Add files via upload
  st.java
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#5 Create fun.py
  fun.py
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#6 Swapping 2 numbers in c++
  swapping.cpp
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#7 Create MErgeMail.py
  Calc.py
  MErgeMail.py
Labels: enhancement, hacktoberfest2022, hacktoberfest2022-accepted

#10 Create selectionsort.py
  selectionsort.py
Labels: good first issue, hacktoberfest2022, hacktoberfest2022-accepted

#9 climbingStairs.cpp
  climbingStairs.cpp
Labels: good first issue, hacktoberfest2022, hacktoberfest2022-accepted

#8 Create hacktoberfest.py
  hacktoberfest.py
Labels: good first issue, hacktoberfest2022, hacktoberfest2022-accepted

#11 Create sort.py
  sort.py
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#12 Create mergeSort.py
  mergeSort.py
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#13 Create newsort.py
  newsort.py
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#14 Create job.cpp
  job.cpp
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#15 Create frist.c
  frist.c
Labels: hacktoberfest2022, hacktoberfest2022-accepted

#16 Create star.c
  star.c
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#17 Create hollow star.c
  hollow star.c
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#18 Create for loop.c
  for loop.c
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#19 Create while loop.c
  while loop.c
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#20 Create first.cpp
  first.cpp
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#21 Create ne.cpp
  ne.cpp
Labels: hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#22 Create newest.cpp
  newest.cpp
Labels: good first issue, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted

#23 Create comparing.cpp
  comparing.cpp
Labels: good first issue, hacktoberfest2022, hacktoberfest2022-accepted, hacktoberfest-accepted
